using System.Collections.ObjectModel;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using FoundrySummarizer.Core.Chat;
using FoundrySummarizer.Core.Routing;
using FoundrySummarizer.Presentation.Services;

namespace FoundrySummarizer.Presentation.ViewModels;

/// <summary>Who wrote a chat message; decides how it is displayed.</summary>
public enum ChatSender
{
    User,
    Assistant,
    Notice,
    Error
}

/// <summary>One message in the chat transcript.</summary>
/// <param name="Sender">Who wrote it.</param>
/// <param name="Text">Message text.</param>
/// <param name="Timestamp">When it was added.</param>
public record ChatMessageItem(ChatSender Sender, string Text, DateTime Timestamp)
{
    /// <summary>True for the user's own questions (shown right-aligned).</summary>
    public bool IsUser => Sender == ChatSender.User;

    /// <summary>Label shown above the message.</summary>
    public string Header => Sender switch
    {
        ChatSender.User => "You",
        ChatSender.Assistant => "Foundry Local",
        ChatSender.Error => "⚠️ Could not answer",
        _ => "ℹ️"
    };
}

/// <summary>
/// Follow-up questions about the loaded document and its summary. Each answer is generated by the local model
/// from the document passages relevant to the question (see <see cref="DocumentChatAgent"/>).
/// </summary>
public partial class ChatViewModel : ObservableObject
{
    private readonly DocumentChatAgent _agent;
    private readonly IFollowUpQuestionGenerator _questionGenerator;
    private readonly IModelReadiness _modelReadiness;
    private readonly IActivityTracker _activity;

    // Cancels suggestion generation for a document or summary that has since been replaced.
    private CancellationTokenSource? _suggestionCts;
    private string _documentText = string.Empty;

    private const string SuggestionsHint = "Summarize the document to get suggested questions about it, or type your own.";

    [ObservableProperty]
    [NotifyCanExecuteChangedFor(nameof(SendMessageCommand))]
    private string _inputQuestion = string.Empty;

    [ObservableProperty]
    [NotifyCanExecuteChangedFor(nameof(SendMessageCommand), nameof(AskSuggestedQuestionCommand), nameof(ClearChatCommand))]
    private bool _hasDocument;

    [ObservableProperty]
    private string _documentName = string.Empty;

    /// <summary>True while the model is answering.</summary>
    [ObservableProperty]
    [NotifyCanExecuteChangedFor(nameof(SendMessageCommand), nameof(AskSuggestedQuestionCommand))]
    private bool _isThinking;

    /// <summary>The conversation, oldest first.</summary>
    public ObservableCollection<ChatMessageItem> Messages { get; } = new();

    /// <summary>One-click questions written by the model for the loaded document (empty until a summary exists).</summary>
    public ObservableCollection<string> SuggestedQuestions { get; } = new();

    /// <summary>Why there are no suggestions yet, or that they are being written; empty when suggestions are shown.</summary>
    [ObservableProperty]
    private string _suggestionsStatus = string.Empty;

    /// <summary>True while the model is writing suggestions.</summary>
    [ObservableProperty]
    private bool _isSuggesting;

    /// <param name="agent">Answers questions about the document.</param>
    /// <param name="questionGenerator">Writes the suggested questions for each document.</param>
    /// <param name="modelReadiness">Questions are disabled until a model is loaded.</param>
    /// <param name="activity">Marks running model work, so the model is not switched meanwhile.</param>
    public ChatViewModel(DocumentChatAgent agent, IFollowUpQuestionGenerator questionGenerator, IModelReadiness modelReadiness, IActivityTracker activity)
    {
        _agent = agent ?? throw new ArgumentNullException(nameof(agent));
        _questionGenerator = questionGenerator ?? throw new ArgumentNullException(nameof(questionGenerator));
        _modelReadiness = modelReadiness;
        _activity = activity;
        _modelReadiness.ReadinessChanged += (_, _) =>
        {
            SendMessageCommand.NotifyCanExecuteChanged();
            AskSuggestedQuestionCommand.NotifyCanExecuteChanged();
        };
        Messages.Add(Notice("Open a document on the Summarize tab, then ask questions about it here."));
    }

    /// <summary>Starts a new conversation about a newly loaded document.</summary>
    /// <param name="documentName">Document name, shown to the user and the model.</param>
    /// <param name="documentText">Full document text the answers are drawn from.</param>
    public void StartSession(string documentName, string documentText)
    {
        _agent.InitializeSession(documentName, documentText, summaryText: string.Empty);
        DocumentName = documentName;
        _documentText = documentText;
        HasDocument = true;

        // The previous document's suggestions no longer apply; new ones are written once this one is summarized.
        _suggestionCts?.Cancel();
        SuggestedQuestions.Clear();
        IsSuggesting = false;
        SuggestionsStatus = SuggestionsHint;
        Messages.Clear();
        Messages.Add(Notice($"Ask anything about '{documentName}'. Answers come only from the document and cite the passages used as [P#]."));
    }

    /// <summary>Gives the model the new summary as context, keeping the conversation so far.</summary>
    /// <param name="summary">The summary just generated for the loaded document.</param>
    public void UpdateSummary(string summary)
    {
        if (!HasDocument) return;
        _agent.UpdateSummary(summary);
        _ = RefreshSuggestionsAsync(summary);
    }

    /// <summary>
    /// Asks the model for questions about this document, based on its summary. Runs after each summary, so the
    /// suggestions follow the document and the summary style; a newer document or summary cancels this run.
    /// </summary>
    private async Task RefreshSuggestionsAsync(string summary)
    {
        _suggestionCts?.Cancel();
        var cts = _suggestionCts = new CancellationTokenSource();

        SuggestedQuestions.Clear();
        IsSuggesting = true;
        SuggestionsStatus = "Writing suggested questions about this document...";
        try
        {
            using var busy = _activity.Begin();
            var questions = await _questionGenerator.SuggestAsync(DocumentName, summary, _documentText, cts.Token);
            if (cts.IsCancellationRequested) return;

            foreach (var question in questions) SuggestedQuestions.Add(question);
            SuggestionsStatus = questions.Count == 0 ? "The model did not suggest any questions. Type your own below." : string.Empty;
        }
        catch (OperationCanceledException) when (cts.IsCancellationRequested)
        {
            // Replaced by a newer document or summary, which shows its own suggestions.
        }
        catch (LocalModelUnavailableException ex)
        {
            if (!cts.IsCancellationRequested) SuggestionsStatus = $"Could not suggest questions: {ex.Message}";
        }
        finally
        {
            if (!cts.IsCancellationRequested) IsSuggesting = false;
        }
    }

    private bool CanAsk() => HasDocument && !IsThinking && _modelReadiness.IsModelReady;

    private bool CanSend() => CanAsk() && !string.IsNullOrWhiteSpace(InputQuestion);

    /// <summary>Sends <see cref="InputQuestion"/> to the model. Cancellable via <c>SendMessageCancelCommand</c>.</summary>
    [RelayCommand(CanExecute = nameof(CanSend), IncludeCancelCommand = true)]
    private async Task SendMessageAsync(CancellationToken cancellationToken)
    {
        var question = InputQuestion.Trim();
        InputQuestion = string.Empty;
        await AskAsync(question, cancellationToken);
    }

    /// <summary>Asks one of <see cref="SuggestedQuestions"/> through the same (cancellable) send path.</summary>
    [RelayCommand(CanExecute = nameof(CanAsk))]
    private async Task AskSuggestedQuestionAsync(string question)
    {
        InputQuestion = question;
        if (SendMessageCommand.CanExecute(null))
        {
            await SendMessageCommand.ExecuteAsync(null);
        }
    }

    /// <summary>Clears the conversation; the document and summary stay loaded, so questions can continue.</summary>
    [RelayCommand(CanExecute = nameof(HasDocument))]
    private void ClearChat()
    {
        _agent.ClearConversation();
        Messages.Clear();
        Messages.Add(Notice($"Conversation cleared. Ask a new question about '{DocumentName}'."));
    }

    private async Task AskAsync(string question, CancellationToken cancellationToken)
    {
        using var busy = _activity.Begin();
        Messages.Add(new ChatMessageItem(ChatSender.User, question, DateTime.Now));
        IsThinking = true;
        try
        {
            var answer = await _agent.AskQuestionAsync(question, cancellationToken);
            Messages.Add(new ChatMessageItem(ChatSender.Assistant,
                string.IsNullOrWhiteSpace(answer) ? "(The model returned an empty answer. Try rephrasing the question.)" : answer.Trim(),
                DateTime.Now));
        }
        catch (OperationCanceledException) when (cancellationToken.IsCancellationRequested)
        {
            Messages.Add(Notice("Question cancelled."));
        }
        catch (LocalModelUnavailableException ex)
        {
            Messages.Add(new ChatMessageItem(ChatSender.Error, ex.Message, DateTime.Now));
        }
        finally
        {
            IsThinking = false;
        }
    }

    private static ChatMessageItem Notice(string text) => new(ChatSender.Notice, text, DateTime.Now);
}
