using System.Collections.ObjectModel;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using FoundrySummarizer.Core.Chat;
using FoundrySummarizer.Core.Routing;

namespace FoundrySummarizer.Wpf.ViewModels;

/// <summary>Who wrote a chat message; decides how it is displayed.</summary>
public enum ChatSender
{
    User,
    Assistant,
    Notice,
    Error
}

/// <summary>One message in the chat transcript.</summary>
/// <param name="Sender">Who wrote it.</param>
/// <param name="Text">Message text.</param>
/// <param name="Timestamp">When it was added.</param>
public record ChatMessageItem(ChatSender Sender, string Text, DateTime Timestamp)
{
    /// <summary>True for the user's own questions (shown right-aligned).</summary>
    public bool IsUser => Sender == ChatSender.User;

    /// <summary>Label shown above the message.</summary>
    public string Header => Sender switch
    {
        ChatSender.User => "You",
        ChatSender.Assistant => "Foundry Local",
        ChatSender.Error => "⚠️ Could not answer",
        _ => "ℹ️"
    };
}

/// <summary>
/// Follow-up questions about the loaded document and its summary. Each answer is generated by the local model
/// from the document passages relevant to the question (see <see cref="DocumentChatAgent"/>).
/// </summary>
public partial class ChatViewModel : ObservableObject
{
    private readonly DocumentChatAgent _agent;

    [ObservableProperty]
    [NotifyCanExecuteChangedFor(nameof(SendMessageCommand))]
    private string _inputQuestion = string.Empty;

    [ObservableProperty]
    [NotifyCanExecuteChangedFor(nameof(SendMessageCommand), nameof(AskSuggestedQuestionCommand), nameof(ClearChatCommand))]
    private bool _hasDocument;

    [ObservableProperty]
    private string _documentName = string.Empty;

    /// <summary>True while the model is answering.</summary>
    [ObservableProperty]
    [NotifyCanExecuteChangedFor(nameof(SendMessageCommand), nameof(AskSuggestedQuestionCommand))]
    private bool _isThinking;

    /// <summary>The conversation, oldest first.</summary>
    public ObservableCollection<ChatMessageItem> Messages { get; } = new();

    /// <summary>Questions that work for most documents, offered as one-click prompts.</summary>
    public IReadOnlyList<string> SuggestedQuestions { get; } = new[]
    {
        "What are the key decisions?",
        "Who is responsible for what, and by when?",
        "What figures and amounts are mentioned?",
        "What risks or open issues are raised?"
    };

    /// <param name="agent">Answers questions about the document.</param>
    public ChatViewModel(DocumentChatAgent agent)
    {
        _agent = agent ?? throw new ArgumentNullException(nameof(agent));
        Messages.Add(Notice("Open a document on the Summarize tab, then ask questions about it here."));
    }

    /// <summary>Starts a new conversation about a newly loaded document.</summary>
    /// <param name="documentName">Document name, shown to the user and the model.</param>
    /// <param name="documentText">Full document text the answers are drawn from.</param>
    public void StartSession(string documentName, string documentText)
    {
        _agent.InitializeSession(documentName, documentText, summaryText: string.Empty);
        DocumentName = documentName;
        HasDocument = true;
        Messages.Clear();
        Messages.Add(Notice($"Ask anything about '{documentName}'. Answers come only from the document and cite the passages used as [P#]."));
    }

    /// <summary>Gives the model the new summary as context, keeping the conversation so far.</summary>
    /// <param name="summary">The summary just generated for the loaded document.</param>
    public void UpdateSummary(string summary)
    {
        if (!HasDocument) return;
        _agent.UpdateSummary(summary);
    }

    private bool CanAsk() => HasDocument && !IsThinking;

    private bool CanSend() => CanAsk() && !string.IsNullOrWhiteSpace(InputQuestion);

    /// <summary>Sends <see cref="InputQuestion"/> to the model. Cancellable via <c>SendMessageCancelCommand</c>.</summary>
    [RelayCommand(CanExecute = nameof(CanSend), IncludeCancelCommand = true)]
    private async Task SendMessageAsync(CancellationToken cancellationToken)
    {
        var question = InputQuestion.Trim();
        InputQuestion = string.Empty;
        await AskAsync(question, cancellationToken);
    }

    /// <summary>Asks one of <see cref="SuggestedQuestions"/> through the same (cancellable) send path.</summary>
    [RelayCommand(CanExecute = nameof(CanAsk))]
    private async Task AskSuggestedQuestionAsync(string question)
    {
        InputQuestion = question;
        if (SendMessageCommand.CanExecute(null))
        {
            await SendMessageCommand.ExecuteAsync(null);
        }
    }

    /// <summary>Clears the conversation; the document and summary stay loaded, so questions can continue.</summary>
    [RelayCommand(CanExecute = nameof(HasDocument))]
    private void ClearChat()
    {
        _agent.ClearConversation();
        Messages.Clear();
        Messages.Add(Notice($"Conversation cleared. Ask a new question about '{DocumentName}'."));
    }

    private async Task AskAsync(string question, CancellationToken cancellationToken)
    {
        Messages.Add(new ChatMessageItem(ChatSender.User, question, DateTime.Now));
        IsThinking = true;
        try
        {
            var answer = await _agent.AskQuestionAsync(question, cancellationToken);
            Messages.Add(new ChatMessageItem(ChatSender.Assistant,
                string.IsNullOrWhiteSpace(answer) ? "(The model returned an empty answer. Try rephrasing the question.)" : answer.Trim(),
                DateTime.Now));
        }
        catch (OperationCanceledException) when (cancellationToken.IsCancellationRequested)
        {
            Messages.Add(Notice("Question cancelled."));
        }
        catch (LocalModelUnavailableException ex)
        {
            Messages.Add(new ChatMessageItem(ChatSender.Error, ex.Message, DateTime.Now));
        }
        finally
        {
            IsThinking = false;
        }
    }

    private static ChatMessageItem Notice(string text) => new(ChatSender.Notice, text, DateTime.Now);
}
